### ISSUE TITLE
switch binding breaks if case-key includes space

### ISSUE THREAD

**Issue by gdibble** [AmpersandJS/ampersand-view#101]
i noticed that when my switch binding case key includes a space, the binding breaks.
specifically 'not sent' >>> 'not\ sent'

workaround:
```javascript
bindings: {
    'model.mediaStatus': {
        type:  'switch',
        cases: {
            'uploading':  '.progress',
            'processing': '.progress',
            'encoding':   '.progress',
            'failed':     '.failed',
/*jshint -W044*/  //ignore warning: Bad or unnecessary escaping.
            'not\ sent':  '.actions',
/*jshint +W044*/
            'finished':   '.actions'
        }
    }
}
```

preferably should not require escaping space,
i found solution by reading code (undocumented - thus as bug, should be fixed)

**Comment by pgilad** [comment]
Added a test case for https://github.com/AmpersandJS/ampersand-dom-bindings/pull/39 and it seems to pass with a space in case...

**Comment by lukekarrys** [comment]
I'm gonna close this since we have a test confirming that is passes now in the dom-bindings lib.
