### ISSUE TITLE
unexpected that `remove` also modifies bindings

### ISSUE THREAD

**Issue by ahdinosaur** [AmpersandJS/ampersand-view#105]
heya, :rabbit2:

i'm trying to `render`, `remove`, and re-`render` a view, however on the re-`render` the bindings don't work as expected. i realize now this is due to `remove` [modifying the bindings](https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L142-L150), but i wonder if there is a better way to do this.

if we want to unlisten and delete bindings in `remove`, is it possible to provide a function that re-listens and re-creates the bindings? or another option is we move that unlisten and delete bindings to another function that maybe can be run by default in `remove` but there is an option to not run it.

cheers, :tea:

**Comment by pgilad** [comment]
This is the updated ref: https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L152-L168

I don't see any reason to leave the bindings if the element has been removed, and you stop listening to events.

If you have a problem with rendering a view that was removed, I'd love to see the use-case and a simple implementation (test-case) of it failing... If the usage is correct there must be some side effect we haven't seen

**Comment by mst7555** [comment]
It looks like a problem I just found with view switcher ;-/  
Switching a view calls view remove what also removes all related event and model bindings. I agree with @pgilad that this behaviour make sense so it should be performed.
The problem is that switching back to such previously removed view do not restore bindings - it just calls view render.
How can I restore all bindings (automatically) in such case?

**Comment by kahnjw** [comment]
This is likely a problem with [ampersand-view-switcher](https://www.npmjs.com/package/ampersand-view-switcher) using the `view.rendered` property to determine whether or not it needs to call `view.render()` on the new view.

The `view.rendered` property will be `true` if `view.el` is defined. `view.el` will be defined even after `view.remove()` is called. This means that when we are "re-rendering" a view with View Switcher, the view's element will be placed in the DOM, but `view.render()` will not be called again, so I think the events are torn down, and never set back up again.

Pretty sure this should be moved to [ampersand-view-switcher](https://www.npmjs.com/package/ampersand-view-switcher).

**Comment by kahnjw** [comment]
Issue: https://github.com/AmpersandJS/ampersand-view-switcher/issues/25

**Comment by cdaringe** [comment]
@ahdinosaur @pgilad,
i agree, this causes issues.  in [ampersand-form-manager-view](http://cdaringe.github.io/ampersand-form-manager-view/) i cycle between forms, meaning I render, remove, and re-render them.  i [reinitialize bindings and subviews](https://github.com/cdaringe/ampersand-form-manager-view/blob/master/ampersand-form-manager-view.js#L133) on each render manually.  the fix may be as easy as pulling out the binding and subview initialization to a helper. then, on render, test if they are set.  if not, re-init them.

**Comment by doubleface** [comment]
I have the same problem as @ahdinosaur. I want be able to rerender a view which has been removed.

Here is my

**Comment by doubleface** [comment]
I have the same problem as @ahdinosaur. I want be able to reuse a view which has been removed. I use the view switcher but I could have the same problem with any other way of switching views which calls the remove method of the view.
Here is an example

```javascript
import View from "ampersand-view";
import ViewSwitcher from "ampersand-view-switcher";

var switcher = new ViewSwitcher(document.querySelector("main"));

var V1 = View.extend({
    session: {
        text: {
            type: "string",
            default: "bonjour"
        }
    },
    bindings: {
        text: ""
    },
    template: `<div>default text v1</div>`
});

var V2 = View.extend({
    template: `<div>default text v2</div>`
});

window.views = [new V1(), new V2()];

var n = 1;
document.addEventListener("click", () => {
    n++;
    switcher.set(views[n % 2]);
});

```

In this example, the bindings do not work after one view switch.

A workaround for this could be to create a new instance of the view each time but  I don't find this satisfying.

And there is already a good solution for the dom events : just call delegateEvents.
A simple createBindings function would also be enough for this need.

Don't you think?
