### ISSUE TITLE
Subview "container" vs "selector" option

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-view#114]
In the documentation, the options for setting up subviews include the following:

>
- container {String} Selector that describes the element within the view that should hold the subview.
- hook {String} Alternate method for specifying a container element using its `data-hook` attribute. Equivalent to `selector: '[data-hook=some-hook]'`.

Is there any reason the `container` option exists, and not the `selector` option, like in other places in  ampersand-*? It's tripped me up a few times, and the line about the `hook` option mentions that it's "equivalent to selector: '[data-hook=some-hook]", which isn't true here.

IMO, the option should be renamed to `selector`, unless there's a functional difference between how `selector` works elsewhere, and how `container` works here in the subview setup.

If the AmpersandJS team agrees, I'll gladly makes the changes and submit a PR.

**Comment by wraithgar** [comment]
Looks like it is just a documentation issue, as it acts as you've described: a selector if it's a string and a container if it's an element.  What it's named under the hood shouldn't matter should it?

In any event as long as the api doesn't change (i.e. no major version bump) I'm +1 on a PR to clean up the language.

**Comment by dhritzkiv** [comment]
Right, so `container` is the incorrect name for the property, since it's not accepting a DOM Element, but a CSS selector string, something that `selector` is better suited for (and is used elsewhere in documentation, and implementation).

See my PR for my proposed solution. It's functionally backwards-compatible, but the Readme now specifies `selector` as the preferred property.
