### ISSUE TITLE
How to use ampersand with reactjs?

### ISSUE THREAD

**Issue by sisardor** [AmpersandJS/ampersand-view#117]
I want to use ampersand in our project, but I want to use ReactJS as rendering engine. How do I use React with ampersand, is there any example I can look at?

**Comment by cquinders** [comment]
@HenrikJoreteg has build a sample app showing just that.
Have a look at https://github.com/henrikjoreteg/hubtags.com

**Comment by cdaringe** [comment]
also check out http://learn.humanjavascript.com/react-ampersand !
