### ISSUE TITLE
ampersand-view is not testable without browserify

### ISSUE THREAD

**Issue by mcous** [AmpersandJS/ampersand-view#118]
I enjoy being able to test the modules that make up my client-side code in an environment that isn't a browser. While it certainly doesn't replace running tests in actual browsers, running tests in node with something like jsdom is still able to give valuable data about a set of tests.

I also really enjoy the modularity that ampersand allows me to bring to the front-end (Seriously though, thanks for all the work that's gone into this). And while testing in node works well with other ampersand modules, ampersand-view has a specific problem that prevents me from doing this. In ampersand-view's dependencies, one can find [delegate-events](https://github.com/HenrikJoreteg/delegate). This module relies on a ["browser" object](https://github.com/HenrikJoreteg/delegate/blob/master/package.json#L6) in its package.json to resolve a [require](https://github.com/HenrikJoreteg/delegate/blob/master/index.js#L6).

Because of this, unless ampersand-view is packaged by browserify (or similar), it will fail spectacularly (or not that spectacularly, but with an error saying `Error: Cannot find module 'event'`). A [pull-request](https://github.com/HenrikJoreteg/delegate/pull/2) that would fix this has been sitting unacknowledged for about eight months now.

Is there anyway that @HenrikJoreteg can merge that PR, or that this problem otherwise fixed?

**Comment by HenrikJoreteg** [comment]
sorry, @mcous and thanks for the detailed explanation. I've published a patch release of `delegate-events` that fixes this. Thanks to semver, you should be able to blow away your node_modules and re-install and things should work. Cheers!

**Comment by mcous** [comment]
Doing that right this second! Big thanks for making my life easier 👍
