### ISSUE TITLE
need a "domready" event hook after calling renderWithTemplate()

### ISSUE THREAD

**Issue by jimthematrix** [AmpersandJS/ampersand-view#124]
I'm trying to use "c3" to render a chart and attach it to a node in the template for the view. in render() I call this.renderWithTemplate() first. then I call c3.generate(). this doesn't work as the dom node doesn't appear to have been inserted when the c3.generate runs. I had to wrap the c3.generate call inside a setTimeout() for this to work.

would be nice to have renderWithTemplate() return a promise that doesn't get fulfilled until the DOM has finished processing, or take a callback.

**Comment by gonsfx** [comment]
Do you instantiate your view with an `el` that is already present in the DOM?

If you do, the view should be inserted in the DOM after `renderWithTemplate` has run because `replaceChild` is invoked when doing so.

**Comment by jimthematrix** [comment]
the view is instantiated as a "partial view" inside a parent view and managed by a ViewSwitcher. so i don't pass in an "el" when instantiating it because it's re-using the one used by the ViewSwitcher.

the sequence goes like this:

- index.html has a .container div
- app.js calls new mainView(), pass in .container as "el", 
- mainView's template has data-hook="page-container"
- mainView.js/render() calls new ViewSwitcher(), pass in queryByHook("page-container")
- router processes a mapped link and calls new FlowView(), which triggers viewSwitcher.set(view)
- Inside the FlowView.js -> render() I have the c3.generate() call

**Comment by gonsfx** [comment]
Is the FlowView set to `autoRender`?

**Comment by jimthematrix** [comment]
nope. it's instantiated by the router, the router triggers a "page" event, which is captured by a listener in the mainView, which calls viewSwitcher.set(flowView). and i guess the ViewSwitcher then calls the render().

**Comment by KayBeSee** [comment]
I'm having a similar issue where I want to render a collection using Kendo UI's Grid but am unable to because the function call gets executed before the content is bound to the DOM. I am using setTimeout(myfunction, 3000) right now but I feel like that's pretty hacky.

I saw this in the Gitter, but it is not working for me still https://gitter.im/AmpersandJS/AmpersandJS?at=54ea685f9d1e094552b0185f

**Comment by pgilad** [comment]
I have used highcharts in combination with a partial view and it works correctly, so it is possible to render on a non-attached dom element and attach it later.

Can you put together a requirebin or some sample code of how you call the `generate` function?

**Comment by tragiclifestories** [comment]
I've had similar issues (particularly to @KayBeSee) and raised a PR against collection view here: https://github.com/AmpersandJS/ampersand-collection-view/pull/40 . 

@pgilad The trouble is that there are (for example) many libraries that do not accept an element as an argument in their constructors, only a selector string or id - if there is nothing that matches that selector, the call will of course fail. IME, these libraries have an unfortunate tendency to be expensive platforms your business has paid a lot of money to use, and thus cannot swap out for something more flexible. :-)

For a top level ampersand-view, we have a great deal of control over how and when it enters the DOM; but the abstractions over subviews sometimes provide less than optimal visibility as to when they are appended to the parent el.

**Comment by pgilad** [comment]
I think what's missing is what I really like about Ember for example - view lifecycles.

**Comment by cdaringe** [comment]
`myView.on('render', initializeYourChart)` should do the trick.  This would not have worked prior to &-view 8.x.  However, so long as your `render` method does attach itself to the DOM, which I'm comfortable claiming is 99% of the time, you should be good to go!  Let me know if that will suffice!
