### ISSUE TITLE
Subviews are not re-rendered on subsequent render() calls in same context

### ISSUE THREAD

**Issue by bryanspears** [AmpersandJS/ampersand-view#126]
I feel like I'm doing something wrong because it's a simple issue to run into.

I've reproduced it many different ways. Calling render back to back, setTimeout then self.render, using view switcher, and more. I noticed on the documentation that it specifically says 

> Not be a problem if it's called more than once.

However, when using the subviews hash, it definitively is a problem to call render more than once.

**Comment by ferdinandsalis** [comment]
I am experiencing the same problem.

**Comment by klaemo** [comment]
Yep, same here. I thought I wasn't understanding subviews correctly.

**Comment by pgilad** [comment]
https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L305

We are unsubscribing from the change event. We should also subscribe to the `rendered` event and keep on listening to it to hook onto `re-renders`. PRs are welcome...

**Comment by bryanspears** [comment]
Just wrote a test to try that. It looks like `change:rendered` is only fired on first render. So it works if you remove then render, but render then render fails.

I see `change:el` is fired. Is it safe to listen for that and then re-render subviews? Or is there a need for a fundamental change to trigger `rendered` when render is called? I'll keep expanding my unit tests to see how it works out.

**Comment by gnimmelf** [comment]
I couldn't work it out properly using the events as suggested by @pgilad, but I managed to put (hack =) together an extension with overrides that at least (initially) works in my case. 

https://gist.github.com/gnimmelf/5ed7df54940c0a2d88bb

I imagine it is in no way perfect, as this is a bit above my level, so all suggestions welcome.

**Comment by cdaringe** [comment]
i posted this elsewhere, in a spot I can no longer find, but I manually force in my `draw` method that all the essential view initialization steps happen: https://github.com/cdaringe/ampersand-form-manager-view/blob/master/ampersand-form-manager-view.js#L133

it's a hack. but it works!

**Comment by gnimmelf** [comment]
@cdaringe cool. The only diff I can tell from my hack is the 'el.on:change' event?
Hope we'll get a more official  fix for this, I don't like hacks I dont trust 100%, especially when they're my own =|

And btw,  nice module,  I allredy know I will need down the road.

**Comment by cdaringe** [comment]
this should be fixed now.  i at some point added the `_upsert` and `_downsert` of the bindings
