### ISSUE TITLE
Extending multiple classes

### ISSUE THREAD

**Issue by herkyl** [AmpersandJS/ampersand-view#131]
I would like to extend multiple classes.

Why using mixins doesn't work for me is because all classes define props and bindings that don't get mixed in.

This is not possible using ampersand-view but maybe someone knows of a module that does this or can redirect me in the right direction.

**Comment by cdaringe** [comment]
sorry for the late response. `.extends` is all we offer at this point.  hopefully you found a way to get what you needed!

**Comment by herkyl** [comment]
Yeah, I created this module https://github.com/Teamweek/ampersand-mixins
