### ISSUE TITLE
Ampersand modules appear to have redudant nested dependencies

### ISSUE THREAD

**Issue by dschissler** [AmpersandJS/ampersand-view#133]
It seems that many of the ampersand components are repeating themselves across many of the modules and this appears to be increasing my Webpack build time.  I suppose that Webpack can remove these repeats by leaving empty stubs in the output.

It seems that if these were listed as peerDependencies then this problem wouldn't exist.

Am I missing something with this?

**Comment by dschissler** [comment]
How will it work when `ampersand-events` is included in bunch of top level modules?  If I update one module that has a newer ampersand-events then would I have two instances of this in my Webpack bundle and two versions of the event object bubbling around in my code?

**Comment by dschissler** [comment]
Is there a convention for preventing dependency hell?

**Comment by cdaringe** [comment]
Are you using npm dedupe or the web pack dedupe plugin?

**Comment by dschissler** [comment]
I'm not in production yet but I'm using the Webpack `DedupePlugin` in the prod/dist profile.  Perhaps I should use it in my dev build as well.  I don't think that it will help with the build time but it probably would prevent some types of issues.

I'm going to explore npm dedupe and sealing as those are new to me.

It seems like npm v3.0 might solve any concerns that I have all in one stroke and also it would make `npm install` quicker.

**Comment by cdaringe** [comment]
Cool.  Let us know how it works for you.

**Comment by dschissler** [comment]
I just upgraded to io.js version 2.3.4 and `npm dedupe` and `npm shrinkwrap` do absolutely nothing to my packages.  For now I'm just accepting the 2x build time by switching to ampersand and I'm hoping that npm v3 solves this issue.  In the meantime as long as I keep a close eye on my package versions then I can let the Webpack DedupePlugin clean up my bundles.  Hopefully npm v3 roles into io.js soon and its everything that it promises to be.
