### ISSUE TITLE
Why is parent not of type "state" by default?

### ISSUE THREAD

**Issue by l337r007** [AmpersandJS/ampersand-view#140]
I was recently wondering why I could not do `bindings` to a parent views model. From studying [the "linking subviews" example](http://codepen.io/imlucas/pen/xbWXNw?editors=001) I finally figured that the bit of extra magic incantation needed was the following:
```js
session: {
	parent: "state"
}
```
Why is this not included in `BaseState` by default? Is it a performance issue? May a view even have a non-`state` parent?

However, my design may also be off: I have two views that depend on the same model, which I figured should best reside in the closest common ancestor of both. Hence the need to bind to a parent model.

**Comment by lukekarrys** [comment]
@l337r007 I've done that in my code before to listen to parent events but I think it is best to leave it as an explicit choice on a per view basis. I think given large enough views and a long enough chain of parents it could lead to perf issues, so it's something I don't think we want to turn on by default.
