### ISSUE TITLE
wait for sync when collection model is destroyed

### ISSUE THREAD

**Issue by tnguyen14** [AmpersandJS/ampersand-view#143]
I am using `renderCollection` to render an `ampersand-rest-collection`. When I destroy a model in the collection, the item is removed from the collection's view. However, when I pass in the option `{wait: true}` for the action and if the server request returns an error, there is no way for me to bring the item back. Is there a way to deal with this situation?

**Comment by pgilad** [comment]
I always destroy with `{wait: true}`. Also - you should listen to `destroy` event, and then either re-render collection or just have the subview remove itself.

**Comment by tnguyen14** [comment]
@pgilad I **do** use `{wait: true}`. Please read the original description again. And the `destroy` event is triggered when the destroy action is called, not when the server responds.

**Comment by pgilad** [comment]
You are quite wrong, the `destroy` event is triggered on model only after the server has responded.
See https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L109

**Comment by tnguyen14** [comment]
You're right. Apologies for misspeaking. I was confusing the `remove` event with the `destroy` event.

However, the issue here is that when the view `renderCollection` with the collection, `ampersand-collection-view` would remove the item view on the `remove` event, which is triggered by the collection. 

On second thought, perhaps this might be the wrong repo to file this bug for (I chose it originally because of the `renderCollection` method)...

**Comment by cdaringe** [comment]
@tnguyen14, agreed.  this is more a BKM question than a bug file.  how to handle async errors is a bit beyond the scope here.  I, for example, use a different version of `sync` which is promisified and `.catch` and restore eager deleted models.  really depends on your app!  closing unless further discussion is needed.  thanks!

**Comment by tnguyen14** [comment]
Thanks. Using promise is an interesting idea. I've been maintaining my own version of `ampersand-sync` that is promisified as well (https://www.npmjs.com/package/ampersand-sync-with-promise).

Just out of curiosity, what is BKM? Also, I wasn't aware that the issue tracker was not meant for question. Apologies.

**Comment by cdaringe** [comment]
apologies for unclear lingo!  BKM => Best Known Method. Questions are fine in here, it's just a long outstanding issue, so i was doing some house keeping :)

**Comment by tnguyen14** [comment]
ok understood. I think my original intention was both asking the question, as well as suggesting if this is something that should be handled specifically in an ampersand package.
