### ISSUE TITLE
List cdaringe as lead maintainer and add him to core team

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-view#144]
Because let's be honest, that's what he's been doing: https://github.com/AmpersandJS/ampersand-view/commits/master

Chris, if you're willing I think it'd be great if you'd take that role. You deserve more credit for all the excellent work you've been doing.

If you're wiling to do this, you should be listed that way in the readme as per: https://github.com/AmpersandJS/examples#examples-patterns-recipes

any thoughts from @AmpersandJS/core-team ?

**Comment by lukekarrys** [comment]
+:100:

**Comment by bear** [comment]
+1

**Comment by wraithgar** [comment]
:shipit:

**Comment by latentflip** [comment]
Huge +1 from me.

Philip Roberts
&yet

**Comment by cdaringe** [comment]
thanks for the support guys :)  i accept

**Comment by HenrikJoreteg** [comment]
woot! https://github.com/AmpersandJS/ampersand-view/commit/70f77ddff2b23559403a7460249eb88288488abd 

will add to main site now too... thanks again @cdaringe!
