### ISSUE TITLE
Possible fix to template engines that attempt to copy the getter-laden context from going crazy 

### ISSUE THREAD

**Issue by dschissler** [AmpersandJS/ampersand-view#147]
I've been looking into how to make Ampersand work with Nunjucks and I think that I have two fixes.  The first one is for allowing nunjucks@2 to understand getters when copying the context and the other is my fix for `renderWithTemplate` in my parent class:

```javascript
      if (context.model) {
        context = {
          model: context.model
        }
      }
```

I'm doing this because it is a huge mess to try and fix a template engine that sanitizes the context to prevent some "leakage".  Apparently they have good reason for that and it seems serious and its a bit out of my domain and really just a huge deviation from what I'm trying to accomplish.

If propose that something like this be done and if there is additional relevant data that could be sent into the template then that could be added.  So just always send a POJO wrapping more complicated properties.  The only downside for this is if someone happens to not be passing in a model and the context happens to have a property named `model`.

**Comment by cdaringe** [comment]
forgive my quick skim, but is calling `model.serialize()` into your template _not_ an option or a solution?

**Comment by dschissler** [comment]
Its not desirably for me because I want to be able to access custom getters and methods on the model.  In particular getting the name of a record/model is a lookup in a `nedb` database and I don't want to do that lazily because a small portion of the models will have a name and I also want to be able to call it with {{ model.name }} and to have that be a getter to all of the magic.  I also want to be able to access DB specific "attributes" on the model by calling `{{ model.getAttr(...) }}.

I'm realizing that there is no hard standard for how a view is to interact with a template engine and so likely there will always be a necessity for a shim.  One example is `ampersand-view` tries to call directly on the template with `.call` and in my case nunjucks is an object that should be called with `render`.  So the native `renderWithTemplate` is inappropriate for me.  In fact the parameters should be swapped since one always needs a template argument and the context is optional in the case of sending in a string.

**Comment by cdaringe** [comment]
if your lib needs pojo and some sort of clean/serialized content, most likely you will have to do some wrapping or proxying of your own.  if you have an explicit suggestion on what &-view can do to help, please let us know
