### ISSUE TITLE
$('.className') vs this.queryByHook('hookName')

### ISSUE THREAD

**Issue by templar112** [AmpersandJS/ampersand-view#148]
When I use JQuery:
  console.log($('.className'));
I get an object (JSON) printed out in the console.

When I use data-hook:
  console.log(this.queryByHook('hookname');
I get HTML DOM printed out in the console.

I'm using Semantic UI and I need to toggle a sidebar control so in query I would use:

// this works
$('.ui.sidebar').sidebar('toggle'); 

// this doesn't
this.queryByHook('sidebar').sidebar('toggle');

How do I achieve what JQuery does without using JQuery?

Thanks,

Oliver

**Comment by wraithgar** [comment]
If you want access to the `sidebar` function, you can wrap the selected element in jquery (or semantic ui, both of which appear to use `$`).

```
$(this.queryByHook('hookname')).sidebar('toggle')
```

**Comment by cdaringe** [comment]
Yep, as wraithgar mentioned.  If you weren't already aware, you can also bind that toggling action to a piece of state in your View as well via the bindings key.  https://github.com/AmpersandJS/ampersand-dom-bindings
