### ISSUE TITLE
Not really strict semver

### ISSUE THREAD

**Issue by phated** [AmpersandJS/ampersand-view#15]
Following semver should include using dependencies that follow semver or locking in dependencies that don't follow semver.  Such as https://github.com/AmpersandJS/ampersand-view/blob/master/package.json#L18. Jeremy has often stated that Underscore does not follow semver which has caused many developers time in the past. E.g. https://github.com/jashkenas/underscore/issues/1684#issuecomment-46197164

**Comment by HenrikJoreteg** [comment]
Cleaning up, this has been resolved for some time now as we're now using lodash individual modules for this.
