### ISSUE TITLE
Using deprecated version of ampersand-state

### ISSUE THREAD

**Issue by timwis** [AmpersandJS/ampersand-view#155]
Forgive me if this is already known, but I tried searching and didn't see it mentioned in this repo. I just typed `npm install --save ampersand-view` on a fresh project and was given the warning:

```
npm WARN deprecated ampersand-state@4.9.1: Breaking changes were inadvertantly introduced in
ampersand-state@4.9.0-1. Please pin your dependency at 4.8.2 or update to ^5.0.0.  See the note 
in the readme for state.set for more info
```

**Comment by wraithgar** [comment]
That version of ampersand-state was released very recently and not all of the things that depend on it have been updated yet.

Unless you're passing complex objects to `.set` you should be fine.  We're still working on updating things to this new version of ampersand-state.  Sorry for the confusion.
