### ISSUE TITLE
get-object-path issues + proposal

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-view#157]
Seems that some of my modules rely on `ampersand-view@v8.*`. However, this version of `ampersand-view` relies on `get-object-path@v0.0.2` (which was unpublished). Any chance for a "maintenance/patch" release (v8.0.2) of `ampersand-view` that depends on `get-object-path` that was republished as v0.0.3?

Not sure if that'll fix install woes.

**Comment by KayBeSee** [comment]
Glad someone else is also experiencing this issue.

I'm trying to deploy on Modulus and it is giving me an error about get-object-path as well because of Ampersand-View. Does anyone know a work around for this?

**Comment by dhritzkiv** [comment]
I managed to get them installing by:

- `rm -rf node_modules`
- `npm install --save ampersand-X@latest`
   - where `X` is the ampersand module name
   - I ran this manually, one-by-one for each ampersand module in my package.json
- `npm install`
   - to retrieve the other, non-ampersand modules

Not sure why trying to `npm install --save ampersand-X@latest ampersand-Y@latest ampersand-Z@latest ...` didn't work.

YMMV, @KayBeSee

**Comment by cdaringe** [comment]
@dhritzkiv, if you want to stage a patched 8.x version, i'd be happy to publish it

**Comment by cdaringe** [comment]
> However, this version of ampersand-view relies on get-object-path@v0.0.2 (which was unpublished)

FTR, the current version (even at the time of issue filing) uses lodash.get

**Comment by dhritzkiv** [comment]
>> However, this version of ampersand-view relies on get-object-path@v0.0.2 (which was unpublished)

> FTR, the current version (even at the time of issue filing) uses lodash.get

Yep. However, non-official ampersand modules may be stuck on ampersand-view < v8.0, and won't install properly (as get-object-path fails)

But I'm now rethinking the efficacy of creating and publishing a patched version of v8, as the majority of 3rd-party ampersand modules may be using versions older than 8: v7, v6, etc. A patch for v8 wouldn't address those versions.

I don't believe there's a way to completely and gracefully recover from the _npm module liberation_ situation. Best to just move on.

**Comment by cdaringe** [comment]
@dhritzkiv, good point, i didn't consider that!
