### ISSUE TITLE
reset() throwing errors since I build from ES6

### ISSUE THREAD

**Issue by ConneXNL** [AmpersandJS/ampersand-view#164]
The following line:
https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L437

throws an error for me since I build with ES6 / Babel (at least I think it happened since that change)
`Uncaught TypeError: Cannot delete property '0' of [object String]`
I have no idea when or why exactly this is but I currently wrapped that block in a try and catch to get rid of the problem.

   ```
     try {
            // TODO: Not sure if this is actually necessary.
            // Just trying to de-reference this potentially large
            // amount of generated functions to avoid memory leaks.
            forEach(parsedBindings, function (properties, modelName) {
                forEach(properties, function (value, key) {
                    delete parsedBindings[modelName][key];
                });
                delete parsedBindings[modelName];
            });
        }catch(err) {}
```

**Comment by cdaringe** [comment]
hey, @ConneXNL, if you can throw an example up on requirebin, that would be excellent!  without an example, i don't have much to work off of.  thanks.  reopen if you think you can post one up.  thanks!

**Comment by gabrielhpugliese** [comment]
I have the exact same problem. I don't really know how to reproduce.

**Comment by dhritzkiv** [comment]
Hey @gabrielhpugliese, are you using the latest version of ampersand-view (10.0.1)? 

If so, could you put up some example code on requirebin or tonicdev? I'd be happy to help track this bug down.

**Comment by gabrielhpugliese** [comment]
No it is the 9.0.2. I will try to upgrade or downgrade the package and keep
you informed. It is very hard to put com a fiddle because it is a big
project.
