### ISSUE TITLE
Release ampersand-*-view

### ISSUE THREAD

**Issue by yamsellem** [AmpersandJS/ampersand-view#168]
Hi,

Can you please release a new version of every `ampersand-*-view` modules with dependency poiting at `ampersand-view` 10.0? It seems that the 10.0 do not bring any breaking changes, so migrating should be painless (hopefully).

Because some module depends on other versions, this add a lot to the bundle size

```javascript
// 418kb 
{
  "ampersand-view": "9.x",
  "ampersand-form-view": "6.x"
}

// 596kb
{
  "ampersand-view": "10.x",
  "ampersand-form-view": "6.x"
}
```

Thanks.

**Comment by cdaringe** [comment]
hi!  this is a very reasonable request.  we don't yet, however, have unified cross package / cross dependency deployment strategy.  this would probably best fall under the bucket of the monorepo/lerna thread taking place i believe over in the &-state repo.  until then, it's up to each &-*-view maintainer on his/her own to deploy.  sorry for the inconvenience!
