### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand-view#176]
Hey @cdaringe! So I went ahead and merged all the greenkeeper PRs which updated all the `ampersand-` dependencies that got updated to Lodash v4.

It ended up not being as straight forward as I thought, so I thought I would open this issue for visibility and to give you a chance to review and then publish/version as you see fit.

Hopefully I didn't step on your toes too much. I was just trying to use my chunk of time to get as much Lodash v4 stuff done as possible.

**Comment by cdaringe** [comment]
@lukekarrys, no sweat. no toe-stepping at all!  it's as much your's as mine as anyone-else's :)

will publish soon
