### ISSUE TITLE
renderSubview expects subview render method to return subview instance

### ISSUE THREAD

**Issue by herkyl** [AmpersandJS/ampersand-view#186]
https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L230

I have not seen this pattern used anywhere else in Ampersand codebase. Should a `render` method always return `this`? And wouldn't it make more sense to just call `render()` and then access `el` like most modules do?

**Comment by wraithgar** [comment]
This is one of the very earliest features that was added to ampersand when it was being forked from backbone.  I think it just worked so well nobody questioned it once we fell into the 'return this' pattern.

If this were changed I would personally prefer exploring whether or not this could be done w/o breaking backwards compatibility.

**Comment by dhritzkiv** [comment]
I agree with this. I believe the code is assuming the default `render` method for views, which always return the view instance (allowing for chaining, as is seen at L230). However, it's easy to forget to return the view in a custom `render` method.

I will quickly make a non-breaking change in the code to be more lax about the return value of `render()`

**Comment by herkyl** [comment]
Thanks @dhritzkiv 
I originally stumbled onto this when implementing a new view module that has the same API as ampersand (internally needed for us for performance), since I didn't return `this` from the render method I got an error.
