### ISSUE TITLE
Looking to become maintainer

### ISSUE THREAD

**Issue by RickButler** [AmpersandJS/ampersand-view#198]
@AmpersandJS/core-team @cdaringe , I would like become maintainer of ampersand-view, as well as  AmpersandJS/ampersand-dom-bindings (I have a comprehensive PR for making ampersand-dom-bindings extensible AmpersandJS/ampersand-dom-bindings#59). 

I'm sure @dhritzkiv could use some help with the maintenance on other packages as well.

(hmm, won't let me @ mention the core team)

**Comment by cdaringe** [comment]
hey @RickButler, yes!  i support this!

**Comment by cdaringe** [comment]
@AmpersandJS/core-team 👀

**Comment by HenrikJoreteg** [comment]
👍

**Comment by cdaringe** [comment]
@RickButler, thanks for stepping up!  You've been added onto this project.

**Comment by RickButler** [comment]
@HenrikJoreteg @cdaringe thanks! I don't know if you do probation period before NPM permissions, but I will probably need those at some point.

https://www.npmjs.com/~rickbutler

**Comment by cdaringe** [comment]
@RickButler, added!  thanks again
