### ISSUE TITLE
Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by mhuggins** [AmpersandJS/ampersand-view#27]
I am trying to set up a simple welcome view (displayed automatically as the root path of my router, can provide that code if needed), but I keep getting this Chrome console error:

> Cannot read property 'model' of undefined

I tried making my code as bear-bones as possible, as you can see.

**views/welcome.js:**

```
var AmpersandView = require('ampersand-view');

module.exports = AmpersandView.extend({
  // I originally defined `el` as 'body' and `render` as a function that renders a React.js
  // component to this.el, but commented it out to demonstrate that that code is unrelated.
});
```

**router.js:**

```
var WelcomeView = require('./views/welcome');

module.exports = AmpersandRouter.extend({
  routes: {
    '': 'welcome'
  },

  welcome: function () {
    new WelcomeView().render();
  }
});
```

**app.js:**

```
var Router = require('./router');

function Application() {
  this.router = new Router();
}

Application.prototype.initialize = function () {
  this.router.history.start({ pushState: true });
  // this.router.navigate('/', { trigger: false });
};

module.exports = Application;
```

**index.js:**

```
var Application = require('./app');

new Application().initialize();
```

The index.js is the starting point, which initializes the app, which in turn initializes the router, which as I understand is automatically loading the root app (my welcome view).  It appears that the `AmpersandView.extend` call is succeeding, while the `new WelcomeView()` call is what's throwing the error.

**Comment by RobertWHurst** [comment]
The following throws `Uncaught TypeError: Cannot read property 'model' of undefined `
```
AmpView.extend({
  model: {}
});
>>
```
You don't even have to do anything with the view, it throws while still in the call stack under the extend call.

**Comment by HenrikJoreteg** [comment]
Thanks everyone. I think we can best address this by improving the messaging in the error that occurs. 

It's happening when trying to `extend()` with something that's already been defined in `props` by a parent. I've proposed a PR to state to address this issue. Closing this one. If you think the PR isn't sufficient to address this issue go ahead and re-open it.
