### ISSUE TITLE
Sensible error should be thrown if the named callback in the event hash is missing.

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersand-view#38]
If the named event in the event hash isn't actually defined on the view, the error message is pretty obscure as it fails all the way down here: https://github.com/HenrikJoreteg/events/blob/master/index.js#L81

We can make that a lot better.

```javascript
events: {
  'click .something': 'someFunctionToRun'
}
```

Related: #37

**Comment by lukekarrys** [comment]
Closed by #106
