### ISSUE TITLE
Hashes (events, bindings, subviews) could be merged with superclass definitions

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand-view#39]
Similar to what is done with session/props/derived on ampersand-state.

I was working on a module recently and had to override View.extend to get this behavior. But in my opinion, I could see this being beneficial to a lot of apps. Thoughts?

**Comment by shaharmor** [comment]
+1

Any update on this?

**Comment by HenrikJoreteg** [comment]
Opted to close the PR implementing this, basically, it can be done manually already. Doing this by default adds a lot of potential for confusion by making it harder to track down what's actually in the final definition.
