### ISSUE TITLE
Shorthands for subview declaration

### ISSUE THREAD

**Issue by janjarfalk** [AmpersandJS/ampersand-view#43]
Wouldn't it be great if you could do like this when you declared subviews?

```javascript
    subviews: {
        status: {
            container: '[role=status]',
            constructor: StatusView,
            // No model is set so it defaults to its parent model.
        }
    }
```

```javascript
    subviews: {
        user: {
            container: '[role=user]',
            constructor: UserView,
            model: 'model.user' // Will set model to model.user and automatically wait for it.
        },
    }
```

```javascript
    subviews: {
        todos: {
            container: '[role=todos]',
            constructor: TodoView,
            collection: 'model.todos' // Will set collection to model.todos and automatically wait for it.
        }
    }
```

Right now it looks like this in my code. 

```javascript
    subviews: {
       status: {
            container: '[role=status]',
            waitFor: 'model',
            prepareView: function (el) {
                return new StatusView({
                    el: el,
                    model: this.model
                });
            }
        },
        user: {
            container: '[role=user]',
            waitFor: 'model.user',
            prepareView: function (el) {
                return new UserView({
                    el: el,
                    model: this.model.user
                });
            }
        },
        todos: {
            container: '[role=todos]',
            constructor: TodoView,
            waitFor: 'model.todos',
            prepareView: function (el) {
                return new TodoView({
                    el: el,
                    collection: this.model.todos
                });
            }
        }
    }
```

I can implement it, but first I would like to know if I missing something and if it is a good idea. What are the downsides to auto assigning parent model as model? What are the downsides to the two new shorthands?

**Comment by gonsfx** [comment]
Seems this isn't in master yet - please merge! :+1:

**Comment by wraithgar** [comment]
That commit is from this branch afaik https://github.com/AmpersandJS/ampersand-view/pull/64 Which has merge conflicts still.  @HenrikJoreteg what are the odds we could take another look at that PR this week?

**Comment by HenrikJoreteg** [comment]
@wraithgar I'm a +1 on simplifying things here, but there's certainly some variance in opinions on how to actually do it, I think that's why things stalled. Philip raised some valid concerns as feedback to my original PR.

**Comment by cdaringe** [comment]
Henrik made some progress on this, but it wasn't quite all there yet.  if someone wants to pick it up and run with it, feel free. however, given that it's not high priority, I am closing out until someone takes the reigns.
