### ISSUE TITLE
Document how to create child collections along with a collection subview.

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersand-view#48]
Basically for people who instinctively want to use something like handlebar's `#each` helper on an array property, demonstrate how to create a child collection instead.

**Comment by cdaringe** [comment]
the [renderCollection](https://github.com/AmpersandJS/ampersand-view#rendercollection-viewrendercollectioncollection-itemview-containerel-viewoptions) docs I think has sufficient content to cover the case. ya, it's not apples-to-apples, but definitely nectarines-to-oranges™
