### ISSUE TITLE
jQuery plugins dont work with event hash

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand-view#72]
In my experience, almost all jQuery plugins use `$(el).trigger('eventname')` to propagate events.

In the Backbone world, these plugins worked with the events hash because under the hood Backbone used `$(el).on` and `$(el).off`. But I think (and I'm not sure why yet) that this doesn't work with [`events-mixin`](https://www.npmjs.org/package/events-mixin) which is what we use under the hood.

To fix this, `delegateEvents` and `undelegateEvents` can be overwritten to use jQuery which isn't too difficult.

But what made it more difficult was that in an app I was switching from Backbone to Ampersand I was using the pattern of making `$el` a derived property (as seen in [`ampersand-view-jquery-mixin`](https://github.com/whobubble/ampersand-view-jquery-mixin/blob/5864cf3b8bf84dbad9d8f21b8baa832e44f262c5/mixin-base.js#L3-L10)). This caused `delegateEvents` to be called when `$el` wasn't ready yet (or it would then be switched out, I'm not sure exactly) which would cause none of the bound events to fire.

That last part is a different issue, but I think is worth documenting (here or elsewhere) because there are so many jQuery plugins out there for tap/swipe events and even more that trigger dom events via jQuery (twitter typeahead, bootstrap, etc).

Overall, I'm not sure what the ideal solution for this is, but it seems like something that a lot of people (especially those migrating old apps) will run into.

**Comment by cdaringe** [comment]
@lukekarrys, is this something we still want to pursue?
