### ISSUE TITLE
mouseenter/mouseleave don't fire for child elements

### ISSUE THREAD

**Issue by nlf** [AmpersandJS/ampersand-view#73]
When binding `mouseenter` and `mouseleave` in a view, due to HTML shenanigans the bindings don't work as expected (like they do in backbone/human-view/other jquery based bindings).

Relevant code bits from jquery:

https://github.com/jquery/jquery/blob/b807aedb7fee321fb3aa5d156a5a256ab0634e2d/src/event.js#L711-L739

**Comment by cdaringe** [comment]
closing as it's dually tracked.  See trello link above.  target is for &-dom-events dep update!
