### ISSUE TITLE
Binding to blur/focus events doesn't work.

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersand-view#8]
And so we begin to run into the things that jQuery did for us...

``` javascript
AmpersandView.extend({
   template: "<div><input class=foo /></div>",
   events: {
      'focus input' : 'doSomething'
   },
   doSomething: function () {
      //I'm never called :(
   }
})
```

Apparently focus/blur events don't bubble in browsers. jQuery fixes this for you transparently, by mapping to focusin/focusout events instead, and I think doing something extra for firefox too because that doesn't support focusin/focusout (https://developer.mozilla.org/en-US/docs/Web/Reference/Events/focus#Event_delegation)

**Comment by adamyonk** [comment]
Looks like this is commented out in master - is there a common workaround for this? focusin/focusout don't have the greatest support.
