### ISSUE TITLE
Emitting events for rendering/inserting

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-view#84]
This is a feature request for emitting events when rendering.

My use case is for `renderCollection()`, as renderCollection can render a collection's existing state, as well as changes to the collection's state in the future. It would be nice to have a `render` event emitted when a round of rendering takes place, and/or an `inserted` event each time a new "ItemView" is rendered.

This would be handy for things like Masonry, which would need to have the newly rendered elements added to its instance in order to lay them out properly.

i.e.:
````javascript
render: {
    this.renderWithTemplate(this);
    var holderElm = this.queryByHook('collection');
    var collectionView = this.renderCollection(this.collection, itemVIew, holderElm);
    var masonry;
    collectionView.on('insert', function(insertedItemView) {
        masonry.addItems(insertedItemView.el);
        masonry.layout();
    });
    masonry = new Masonry(holderElm);
}
````

**Comment by imlucas** [comment]
You can already do this in a by listening for `change:rendered`.  I use this trick all the time for bootstrap, jquery plugins, d3, etc.  Don't know if this is closable though as `change:rendered` is currently undocumented.

```javascript
var raf = require('component-raf');
var Masonry = require('masonry');
var AmpersandCollection = require('ampersand-collection');
var AmpersandView = require('ampersand-view');
var AmpersandModel = require('ampersand=model');

var ItemCollection = AmpersandCollection.extend({
  model: AmpersandModel.extend({
    props: {
      id: 'number',
      content: 'string'
    }
  }),
  fetch: function(options){
    var collection = this;
    raf(function(){
      var resp = [
        {id: 1, content: 'Item 1'},
        {id: 2, content: 'Item 2'},
        {id: 3, content: 'Item 3'}
      ];
      collection.trigger('sync', collection, resp, options);
    });
  }
});

var GridItemView = AmpersandView.extend({
  initialize: function(){
    // When this view's `el` is about to be available in the DOM,
    // `rendered` will be set to true, causing a change event.
    this.listenTo(this, 'change:rendered', this._addToMasonry);
  },
  _addToMasonry: function(){
    var view = this;
    // `this.parent` is an instance of `GridView` and is set by `renderCollection`.
    var masonry = this.parent.masonry;

    // Defer to the next event loop call when `this.el` will definitely
    // be available.
    raf(function(){
      masonry.addItems(view.el);
      masonry.layout();
    });
  }
});

var GridView = AmpersandView.extend({
  collections: {
    items: ItemCollection
  },
  template: '<ul data-hook="grid"></ul>',
  initialize: function(){
    this.items.fetch();
  },
  render: function(){
    this.renderWithTemplate();

    var gridEl = this.queryByHook('grid');
    this.masonry = new Masonry(gridEl);
    this.renderCollection(this.items, GridItemView, gridEl);
  }
});
```

**Comment by dhritzkiv** [comment]
@imlucas Thanks for the tip! 

Here, the `change:rendered` event works on the newly inserted item views, which is not ideal, but does seems like a good work-around in the meantime. Perhaps, based on this, I can find a way to have the item views report/trigger an event on their parent (collection-view) and listen to that instead.

**Comment by imlucas** [comment]
@dhritzkiv np.  here's another example that might be helpful (say you want to communicate between child and parent, or have a child communicate with any other children that have the same parent):

[Linking subviews in ampersand.js](http://codepen.io/imlucas/pen/xbWXNw)

**Comment by bryanspears** [comment]
I've found a legitimate issue with the render event. Maybe it's related to input-view as a subview, which is unlikely as that's all top-down, synchronous rendering code, but I've had quirks with listening to 'render' before where I couldn't take dom action on an element.

If you try to focus an input field "on render" (or in the render method) it will fail. You have to bump execution to the end of the stack with a setTimeout 0 (or setImmediate or lodash delay, etc.)

Either the render event needs more intelligence to detect when dom elements are truly "ready" or bake in the setTimeout 0 to the render or a new event.

**Comment by cdaringe** [comment]
hey @bryanspears.  keep in mind that `rendered !== attached`.  `rendered` being emitted does not 100% guarantee that your content will be on the DOM.  _most of the time_, it's the case.  perhaps there's a requirebin ex we can get goin' to diagnose?

**Comment by bryanspears** [comment]
Of course, it works on requirebin -- http://requirebin.com/?gist=ddd2be061e7a7f5418d3

I already double checked for tabindex, focus(), and the other usual problems with browser focus issues. I guess this one is stuck until I figure out why.

**Comment by cdaringe** [comment]
yea @bryanspears, if it's synchronous the whole way though, i agree, you shouldn't have issue.  async `render`s will definitely ruin your day though!  @dhritzkiv, there is a dupe thread about wanting events from `renderCollection` items.  i definitely get the semantic desire to do `collectionView.views.on(...)`.  I think if someone wants to take a stab at updating &-collection-view, it could use some love!  for now, however, as the issue really resides in the other module's capability, i'm going to close this one out.  we can re-open as needed
