### ISSUE TITLE
Force trigger bindings

### ISSUE THREAD

**Issue by herkyl** [AmpersandJS/ampersand-view#86]
Is it possible to trigger all bindings on an object. Some of the bindings get messed up after I resize the window (because they set the width and height of elements).

**Comment by lukekarrys** [comment]
Sorry for the delay in answering this. There is an internal method `_applyBindingsForKey(keyName)` which could be used in this case. It's prefixed with a `_` so its only being used as an internal method currently, and is subject to break in less than major semver updates, so use with caution.

How I've worked around this in the past is to create a window resize listener and within the handler for that set a session property in the view. Then you could base your other bindings on that session property.

Hope this helps!

**Comment by EvanCarroll** [comment]
If you supply a model to a view with values already set, are the bindings supposed to trigger automagically? Or, do they only trigger when they're set afterward?

**Comment by herkyl** [comment]
@EvanCarroll They are triggered on creation of the view and when changes occur.
