### ISSUE TITLE
Namespace collision warnings

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-view#96]
When registering things like subviews, the names in the hash are blindly applied to this, which could collide with things like props or session variables, it would be kind to the dev if there were some sort of order of precedence for those (i.e. props are always set, subviews throw if a prop exists in that namespace already).

This may also need to be functionality that's pushed down into ampersand-state (like having a `safe-set` internal function that ampersand-view can use when setting things like subviews to the local namespace).

**Comment by pgilad** [comment]
@wraithgar I've made an initial attempt at this: https://github.com/AmpersandJS/ampersand-view/pull/128

Can you go over it?

**Comment by gonsfx** [comment]
Is it really necessary to access a subview named `form` as `this.form`?

Wouldn't it be appropriate to have a `subviews` prop (type: 'object') and to access a subview named `form` as `this.subviews.form`?
