### ISSUE TITLE
Changes to model in the intialize function of view overriden

### ISSUE THREAD

**Issue by josh-bradley** [AmpersandJS/ampersand-view#98]
I'm getting an issue where if I set the model as part of the options when newing up a view and then make changes to the model in the initialize method of the view my changes are overridden by the original value passed in as options.

**Comment by pgilad** [comment]
This will be solved by: https://github.com/AmpersandJS/ampersand-view/pull/103

**Comment by pgilad** [comment]
Solved by 694c54e8639be9c7849ba149c7790af608e7d491
